---
swagger: "2.0"
info:
  description: The Fraud Alert RESTful API provides integration partners the ability to retrieve case data for fraudulent cases, and notify Fiserv of the results from the notifications to close a fraud case.
  version: 2.0.0
  title: 'Card Risk Mitigation: Fraud Alert API'
host: card.api.fiservapps.com
basePath: /cs/fraudDeprecated
tags:
- name: Fraud Alerts
schemes:
- https
security:
- BearerToken: []
paths:
  /v1/case/search:
    post:
      tags:
      - Fraud Alerts
      x-child-product-name: Fraud Alerts v2.0.0
      x-group-name: Case
      x-proxy-name: Get Case Info
      summary: Retrieve current fraud case information from Fiserv.
      operationId: getCaseInfo
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: x-fapi-financial-id
        in: header
        description: Required. Enter the client id.
        required: true
        type: string
        maxLength: 8
        minLength: 1
        pattern: ^[0-9]*$
      - name: x-fapi-interaction-id
        in: header
        description: Enter the transaction/correlation id
        required: false
        type: string
        maxLength: 40
        minLength: 15
        pattern: ^[^-][a-zA-Z0-9-][^-]$
      - name: Authorization
        in: header
        description: 'Enter ''Bearer '' followed by the access token. Please refer to documentation on bearer token. '
        required: true
        type: string
        maxLength: 128
        minLength: 43
        pattern: ^[a-zA-Z0-9-._~]$
      - in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/GetFraudCaseInfoRequest'
      responses:
        "200":
          description: Success
          headers:
            x-fapi-interaction-id:
              type: string
              description: Represents a transaction ID created with each request
          schema:
            $ref: '#/definitions/GetFraudCaseInfoResponse'
        "400":
          description: Bad Request
          headers:
            x-fapi-interaction-id:
              type: string
              description: transaction ID created with each request
          schema:
            type: object
            example:
              errors:
              - code: WS100
                description: Information entered is invalid-please revise and try again
        "401":
          description: Unauthorized access
          schema:
            type: object
            example:
              errors:
              - code: 401
                description: Invalid access token
        "404":
          description: Resource Not Found
        "415":
          description: Unsupported Media Type
          headers:
            x-fapi-interaction-id:
              type: string
              description: transaction ID created with each request
          schema:
            type: object
            example:
              errors:
              - code: 415
                description: unsupported Media Type
        "429":
          description: Too Many Requests
          headers:
            x-fapi-interaction-id:
              type: string
              description: transaction ID created with each request
          schema:
            type: object
            example:
              errors:
              - code: 429
                description: Rate limit quota violation. Quota limit  exceeded.
        "500":
          description: Server Error
          headers:
            x-fapi-interaction-id:
              type: string
              description: transaction ID created with each request
          schema:
            type: object
            example:
              errorResponse:
                code: 500-01
                message: internal server error
                developerInfo:
                  developerMessage: internal server error
                  moreInfo: There was a problem handling your request.  Please try again.  If the problem persists please contact Fiserv ETSD at 888-243-2543 (you unique messageID included below)
                  messageid: 25557-84290371-1
  /v1/alertOutcome:
    put:
      tags:
      - Fraud Alerts
      x-child-product-name: Fraud Alerts v2.0.0
      x-group-name: Alert
      x-proxy-name: Alert Outcome
      summary: Enable business partners to notify Fiserv of updates to a case under review. Fiserv returns a response that identifies if a case outcome request is accepted or rejected and, if rejected, the reason why.
      operationId: alertOutcome
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: x-fapi-financial-id
        in: header
        description: Required. Enter the client id.
        required: true
        type: string
        maxLength: 8
        minLength: 1
        pattern: ^[0-9]*$
      - name: x-fapi-interaction-id
        in: header
        description: Enter the transaction/correlation id
        required: false
        type: string
        maxLength: 40
        minLength: 15
        pattern: ^[^-][a-zA-Z0-9-][^-]$
      - name: Authorization
        in: header
        description: 'Enter ''Bearer '' followed by the access token. Please refer to documentation on bearer token. '
        required: true
        type: string
        maxLength: 128
        minLength: 43
        pattern: ^[a-zA-Z0-9-._~]$
      - in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/FraudAlertOutcomeRequest'
      responses:
        "200":
          description: Success
          headers:
            x-fapi-interaction-id:
              type: string
              description: Represents a transaction ID created with each request
        "400":
          description: Bad Request
          headers:
            x-fapi-interaction-id:
              type: string
              description: transaction ID created with each request
          schema:
            type: object
            example:
              errors:
              - code: WS100
                description: Information entered is invalid-please revise and try again
        "401":
          description: Unauthorized access
          schema:
            type: object
            example:
              errors:
              - code: 401
                description: Invalid access token
        "404":
          description: Resource Not Found
        "415":
          description: Unsupported Media Type
          headers:
            x-fapi-interaction-id:
              type: string
              description: transaction ID created with each request
          schema:
            type: object
            example:
              errors:
              - code: 415
                description: unsupported Media Type
        "429":
          description: Too Many Requests
          headers:
            x-fapi-interaction-id:
              type: string
              description: transaction ID created with each request
          schema:
            type: object
            example:
              errors:
              - code: 429
                description: Rate limit quota violation. Quota limit  exceeded.
        "500":
          description: Server Error
          headers:
            x-fapi-interaction-id:
              type: string
              description: transaction ID created with each request
          schema:
            type: object
            example:
              errorResponse:
                code: 500-01
                message: internal server error
                developerInfo:
                  developerMessage: internal server error
                  moreInfo: There was a problem handling your request.  Please try again.  If the problem persists please contact Fiserv ETSD at 888-243-2543 (you unique messageID included below)
                  messageid: 25557-84290371-1
  /v1/caseClose:
    put:
      tags:
      - Fraud Alerts
      x-child-product-name: Fraud Alerts v2.0.0
      x-group-name: Case
      x-proxy-name: Close Case
      summary: Notify Fiserv if a case for Fraud Alert is closed on the vendor platform.
      operationId: closeCase
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: x-fapi-financial-id
        in: header
        description: Required. Enter the client id.
        required: true
        type: string
        maxLength: 8
        minLength: 1
        pattern: ^[0-9]*$
      - name: x-fapi-interaction-id
        in: header
        description: Enter the transaction/correlation id
        required: false
        type: string
        maxLength: 40
        minLength: 15
        pattern: ^[^-][a-zA-Z0-9-][^-]$
      - name: Authorization
        in: header
        description: 'Enter ''Bearer '' followed by the access token. Please refer to documentation on bearer token. '
        required: true
        type: string
        maxLength: 128
        minLength: 43
        pattern: ^[a-zA-Z0-9-._~]$
      - in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/FraudCloseCaseRequest'
      responses:
        "200":
          description: Success
          headers:
            x-fapi-interaction-id:
              type: string
              description: Represents a transaction ID created with each request
        "400":
          description: Bad Request
          headers:
            x-fapi-interaction-id:
              type: string
              description: transaction ID created with each request
          schema:
            type: object
            example:
              errors:
              - code: WS100
                description: Information entered is invalid-please revise and try again
        "401":
          description: Unauthorized access
          schema:
            type: object
            example:
              errors:
              - code: 401
                description: Invalid access token
        "404":
          description: Resource Not Found
        "415":
          description: Unsupported Media Type
          headers:
            x-fapi-interaction-id:
              type: string
              description: transaction ID created with each request
          schema:
            type: object
            example:
              errors:
              - code: 415
                description: unsupported Media Type
        "429":
          description: Too Many Requests
          headers:
            x-fapi-interaction-id:
              type: string
              description: transaction ID created with each request
          schema:
            type: object
            example:
              errors:
              - code: 429
                description: Rate limit quota violation. Quota limit  exceeded.
        "500":
          description: Server Error
          headers:
            x-fapi-interaction-id:
              type: string
              description: transaction ID created with each request
          schema:
            type: object
            example:
              errorResponse:
                code: 500-01
                message: internal server error
                developerInfo:
                  developerMessage: internal server error
                  moreInfo: There was a problem handling your request.  Please try again.  If the problem persists please contact Fiserv ETSD at 888-243-2543 (you unique messageID included below)
                  messageid: 25557-84290371-1
securityDefinitions:
  BearerToken:
    description: Enter 'Bearer ' followed by the access token.
    type: apiKey
    name: Authorization
    in: header
definitions:
  GetFraudCaseInfoRequest:
    type: object
    required:
    - caseID
    - clientApplicationName
    - clientAuditId
    - clientId
    - clientVendorName
    properties:
      clientId:
        type: string
        example: "07100015"
        description: The Card Services identifier for a given financial institution
        maxLength: 8
      clientApplicationName:
        type: string
        example: FRAUDALERTRWS
        description: Client application identifier
        maxLength: 50
      clientVendorName:
        type: string
        example: ABC VENDOR
        description: Client vendor identifier
        maxLength: 30
      clientAuditId:
        type: string
        example: Maria
        description: Identifies the entity on whose behalf the request is made.  This value often identifies a User
        maxLength: 13
      systemRecordIdentifier:
        type: string
        example: /XpwDirKMMx5Svoi48Y/n7VB8mzZRcJndyFgFuL/LPCT/dnqH2Gi2OwOIriS8Vtt
        description: Key value that is returned by the client in the subsequent update request and must not be edited
        maxLength: 41
      caseID:
        type: string
        example: "60384538"
        description: Unique identifier for this case. The caseID is the combination of a 2–character schema id associated with the Falcon 6 tenant identifier and the caseNumber.
        maxLength: 14
  GetFraudCaseInfoResponse:
    type: object
    required:
    - caseData
    - tranData
    properties:
      caseData:
        $ref: '#/definitions/GetCaseInfoCaseItem'
      tranData:
        $ref: '#/definitions/Transaction'
  FraudAlertOutcomeRequest:
    type: object
    required:
    - caseData
    - clientApplicationName
    - clientAuditId
    - clientId
    - clientVendorName
    - notificationTimestamp
    - response
    - tranResult
    properties:
      clientId:
        type: string
        example: "07100015"
        description: The Card Services identifier for a given financial institution
        maxLength: 8
      clientApplicationName:
        type: string
        example: FRAUDALERTRWS
        description: Client application identifier
        maxLength: 50
      clientVendorName:
        type: string
        example: ABC VENDOR
        description: Client vendor identifier
        maxLength: 30
      clientAuditId:
        type: string
        example: Maria
        description: Identifies the entity on whose behalf the request is made.  This value often identifies a User
        maxLength: 13
      systemRecordIdentifier:
        type: string
        example: /XpwDirKMMx5Svoi48Y/n7VB8mzZRcJndyFgFuL/LPCT/dnqH2Gi2OwOIriS8Vtt
        description: Key value that is returned by the client in the subsequent update request and must not be edited
        maxLength: 41
      caseData:
        $ref: '#/definitions/AlertOutComeCaseItem'
      tranResult:
        $ref: '#/definitions/TransactionResult'
      cardStatusAction:
        type: string
        example: BLOCK
        description: Distinguishes that the caller has made the appropriate decisions on the transactions they just heard in the IVR and thus an attempt should be made to change the card status
        enum:
        - UNBLOCK
        - BLOCK
      response:
        $ref: '#/definitions/Result'
      subResponse:
        $ref: '#/definitions/SubResult'
      notificationTimestamp:
        type: string
        format: yyyy-mm-ddThh:mm:ss
        example: 2018-04-13T10:06:02.197-04:00
        description: Date/time associated with the customer response; not the system insert time
  FraudCloseCaseRequest:
    type: object
    required:
    - caseData
    - caseFinish
    - caseResultData
    - clientApplicationName
    - clientAuditId
    - clientId
    - clientVendorName
    properties:
      clientId:
        type: string
        example: "07100015"
        description: The Card Services identifier for a given financial institution
        maxLength: 8
      clientApplicationName:
        type: string
        example: FRAUDALERTRWS
        description: Client application identifier
        maxLength: 50
      clientVendorName:
        type: string
        example: ABC VENDOR
        description: Client vendor identifier
        maxLength: 30
      clientAuditId:
        type: string
        example: Maria
        description: Identifies the entity on whose behalf the request is made.  This value often identifies a User
        maxLength: 13
      systemRecordIdentifier:
        type: string
        example: /XpwDirKMMx5Svoi48Y/n7VB8mzZRcJndyFgFuL/LPCT/dnqH2Gi2OwOIriS8Vtt
        description: Key value that is returned by the client in the subsequent update request and must not be edited
        maxLength: 41
      caseData:
        $ref: '#/definitions/CaseCloseCaseItem'
      caseResultData:
        $ref: '#/definitions/Result'
      caseFinish:
        type: string
        format: yyyy-mm-ddThh:mm:ss
        example: 2019-06-18T16:18:02.197-04:00
        description: Date/time associated with the case close response; not the system insert time
  AlertOutComeCaseItem:
    type: object
    required:
    - caseID
    - lastUpdated
    properties:
      caseID:
        type: string
        example: "60384538"
        description: Unique identifier for this case. The caseID is the combination of a 2–character schema id associated with the Falcon 6 tenant identifier and the caseNumber.
        maxLength: 14
      lastUpdated:
        type: string
        format: yyyy-mm-ddThh:mm:ss
        example: 2019-07-26T11:43:34.291-04:00
        description: The last date and time the case was updated
    description: This data structure holds the basic information about the case
  CaseCloseCaseItem:
    type: object
    required:
    - caseID
    - lastUpdated
    properties:
      caseID:
        type: string
        example: "60384538"
        description: Unique identifier for this case. The caseID is the combination of a 2 character schema id associated with the Falcon 6 tenant identifier and the caseNumber.
        maxLength: 14
      lastUpdated:
        type: string
        format: yyyy-mm-ddThh:mm:ss
        example: 2019-07-26T11:43:34.291-04:00
        description: The last date and time the case was updated
    description: This data structure holds the basic information about the case
  GetCaseInfoCaseItem:
    type: array
    items:
      $ref: '#/definitions/GetCaseInfoCaseItemObj'
  GetCaseInfoCaseItemObj:
    type: object
    required:
    - caseID
    - lastUpdated
    - workflowCode
    properties:
      caseID:
        type: string
        example: "60384538"
        description: Unique identifier for this case. The caseID is the combination of a 2character schema id associated with the Falcon 6 tenant identifier and the caseNumber
        maxLength: 14
      workflowCode:
        type: string
        example: "14"
        description: Workflow used for processing this notification
        maxLength: 2
      lastUpdated:
        type: string
        format: yyyy-mm-ddThh:mm:ss
        example: 2019-07-26T11:43:34.291-04:00
        description: The last date and time the case was updated
    description: This data structure holds the basic information about the case
  Transaction:
    type: array
    description: 'Contains information about suspect transactions. Repeats up to 3 times. Note: The selection criteria for the 3 transactions should be identical to the Nuance selection criteria'
    items:
      $ref: '#/definitions/TransactionObj'
  TransactionObj:
    type: object
    required:
    - tranAmount
    - tranDate
    - tranId
    properties:
      tranId:
        type: string
        example: 016001da2e000044
        description: The transaction’s identification number – unique across all clients / cardholders
        maxLength: 18
      tranDate:
        type: string
        format: yyyy-mm-ddThh:mm:ss
        example: 2019-07-26T07:22:04.000-04:00
        description: The date the transaction was processed by authorization system
      tranAmount:
        type: number
        format: double
        example: 600.0
        description: The total amount of the transaction
      merchantName:
        type: string
        example: NETFLIX COM
        description: The merchant that processed the transaction
        maxLength: 40
      merchantCity:
        type: string
        example: LOS GATOS
        description: The city of the merchant
        maxLength: 30
      merchantState:
        type: string
        example: CA
        description: The state of the merchant
        maxLength: 3
      merchantCntry:
        type: string
        example: "840"
        description: A code representing the country of the merchant – will send alphanumeric
      tranMcc:
        type: string
        example: "4899"
        description: MCC – Merchant Category Code
        maxLength: 4
      decisionCode:
        type: string
        example: D
        description: A code to indicate whether or not the transaction was A(approved) or D(denied)
        maxLength: 1
        enum:
        - A
        - D
  TransactionResult:
    type: array
    description: This data structure holds the response from the cardholder for the suspect transactions. Repeats up to 3 times
    items:
      $ref: '#/definitions/TranResultItem'
  TranResultItem:
    type: object
    required:
    - number
    - result
    properties:
      number:
        type: string
        example: "177185"
        description: The transaction’s identification number – unique across all clients / cardholders
        maxLength: 18
      result:
        type: string
        example: NO_FRAUD
        description: The outcome of what choice the caller made to the Alert Notification Vendor when presented with a transaction – this value is used to “tag” the transaction within EnFact
        enum:
        - FRAUD
        - NO_FRAUD
  Result:
    type: object
    required:
    - code
    properties:
      code:
        type: string
        example: "61"
        description: Value of the Vendor Result code or the Result Sub code
      description:
        type: string
        example: Fraud
        description: Reason for sending the Code
    description: May get multiple responses per contact, but will only get one per message
  SubResult:
    type: object
    properties:
      code:
        type: string
        example: ""
        description: Value of the Vendor Result code or the Result Sub code
      description:
        type: string
        example: ""
        description: Reason for sending the Code
    description: May get multiple responses per contact, but will only get one per message
