################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################

openapi: 3.0.3
info:
  title: Care Developer Test
  description: V10 open API document.
  version: 1.0.0
servers:
  - url: 'http://204.105.107.65:24500/fva_apac/'
paths:
  /v1/accounts/blockUnblock:
    patch:
      tags:
        - Account Management
      x-group-name: Account Management
      x-proxy-name: Block-Unblock Account
      summary: Block-Unblock Account
      description: This service is used to update the Account Block Code
      operationId: blockUnblock
      parameters:
        - name: X-Correl-Id
          in: header
          description: >-
            Any correlational text client's may want to send in the request for
            mapping the response on their side. Any value passed in the request
            message will be return back as-is in the API response message
          schema:
            maxLength: 40
            minLength: 0
            type: string
            example: EXC-ID-12345678-SUB
        - name: X-Name
          in: header
          required: true
          description: >-
            User’s sign-on name. The value passed in this field will be
            validated within application for user's authority to consume the
            requested API
          schema:
            maxLength: 30
            minLength: 0
            type: string
            example: John Smith
        - name: X-context
          in: header
          required: true
          description: >-
            A unique random ID assigned to the requestor once authenticated to
            the First Vision application. Value passed in this field will be
            used within application to authenticate the valid signed-on user
          schema:
            maxLength: 20
            minLength: 0
            type: string
            example: 00001AUVMX
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountsBlockUnblockReq'
            examples:
              BlockAccount:
                $ref: '#/components/examples/BlockAccount'
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountsBlockUnblockResp'
              examples:
                BlockAccount:
                  $ref: '#/components/examples/BlockAccount'
        '400':
          description: The request cannot be validated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList1'
              examples:
                '400':
                  $ref: '#/components/examples/400-Errors'
        '401':
          description: The request was unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList1'
              examples:
                '401':
                  $ref: '#/components/examples/401-Errors'
        '404':
          description: The request resource does not exist
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList1'
              examples:
                '401':
                  $ref: '#/components/examples/404-Errors'
        '500':
          description: An unexpected internal server error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList1'
              examples:
                '500':
                  $ref: '#/components/examples/500-Errors'
        '503':
          description: The service was unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList1'
              examples:
                '503':
                  $ref: '#/components/examples/503-Errors'
        '504':
          description: The request timed out while waiting for a response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorList1'
              examples:
                '504':
                  $ref: '#/components/examples/504-Errors'
components:
  schemas:
    CardsSecureCodeReq:
      required:
        - businessUnit
        - cVV2
        - cardNumber
      type: object
      properties:
        cVV2:
          maxLength: 3
          type: string
          description: CVV2-valid CVV2 should be entered printed on the card
          format: uppercase
        expiryDateMMYY:
          maxLength: 4
          type: string
          description: >-
            Expire Date-valid card expire date should be provided which is of 4
            character with MMYY format
          format: uppercase
        businessUnit:
          maximum: 999
          minimum: 0
          type: number
          description: >-
            Business Unit -Identification number of the organization associated
            with thisAccount Base Segment record. The values are 001–998.
        signonName:
          type: string
          description: Signon name
        securitySignon:
          type: string
          description: Security signon
        cardNumber:
          maxLength: 19
          type: string
          description: >-
            Card Number -Number that is embossed on the plastic card. Enter a
            value inthis field only if the card number is different from the
            post-toaccount number
          format: uppercase
    CardsClearReq:
      required:
        - indicator
        - businessUnit
        - cardNumber
      type: object
      properties:
        cardNumber:
          type: string
          description: Clear Pan - 19 digit Clear card number
          format: uppercase
        indicator:
          type: string
          description: Indicator - Value 'Y' should be passed
        businessUnit:
          type: number
          description: >-
            Business Unit: Identification number of the organization associated
            with thisAccount Base Segment record,The values are 001–998
    cardsClearResponse:
      type: object
      properties:
        cardNumber:
          type: string
          description: Clear Pan - 19 digit Clear card number
          format: uppercase
    UpdateCardStatusReq:
      required:
        - businessUnit
        - postToAccountNumber
        - cardNumber
        - cardSequence
      type: object
      properties:
        businessUnit:
          type: number
          description: >-
            Business Unit: Identification number of the organization associated
            with thisAccount Base Segment record,The values are 001–998
        cardNumber:
          type: string
          description: Clear Pan - 19 digit Clear card number
          format: uppercase
        cardSequence:
          type: string
          description: Card sequence- This a static value value 0001 should be passed
        postToAccountNumber:
          type: string
          description: >-
            Post to account number-Identification number of the Account
            BaseSegment record towhich CMS posts transactio received for this
            Embosser record
    UpdateCardStatusResp:
      required:
        - businessUnit
        - postToAccountNumber
        - cardNumber
        - cardSequence
      type: object
      properties:
        businessUnit:
          type: number
          description: >-
            Business Unit: Identification number of the organization associated
            with thisAccount Base Segment record,The values are 001–998
        cardSequence:
          type: number
          description: Card sequence- This a static value value 0001 should be passed
        postToAccountNumber:
          type: string
          description: >-
            Post to account number-Identification number of the Account Base
            Segment record towhich CMS posts transactions received for this
            Embosser record
          maxLength: 19
        cardNumber:
          type: string
          description: >-
            CARD NUMBER-Number that is embossed on the plastic card. Enter a
            value inthis field only if the card number is different from the
            post-toaccount number
          maxLength: 19
    ErrorList:
      type: array
      items:
        type: object
        properties:
          err_code:
            type: string
            description: Error Codes
          error_message:
            type: string
            description: ' Error Description'
    UpdateCardTransferResp:
      required:
        - cardNumber
      type: object
      properties:
        blockCode:
          type: string
          description: >-
            Block Code- Block code of OLD card or fraud card this can be any
            value from A TO Z
          format: uppercase
        errorDescription:
          type: string
          description: Error description
        errorType:
          type: string
          description: Error Type
        serviceReturnCode:
          type: string
          description: >-
            Service Return Code- This is specific to API return code the values
            are P AND F
        transactionReturnCode:
          type: string
          description: Transaction return code
        errorCode:
          type: string
          description: Error code
        maskCardnumber:
          type: string
          description: >-
            Mask Pan Number- The clear card number will be masked with XXXX from
            9 didgit to 15th didgit
          format: uppercase
        numberOfErrors:
          type: string
          description: >-
            Number of errors- This will displays the number of errors in the
            service This is an occur cause which can store maxmum 20 erros
        transferToAccount:
          type: string
          description: Transfer To Account- The account asscoicated to the old card
          format: uppercase
        transferToCustomer:
          type: string
          description: Transfer To Customer-The customer asscoicated to the old card
          format: uppercase
        applicationReturnCode:
          type: string
          description: Application Return code
        systemReturnCode:
          type: string
          description: System retrun code
        cardNumber:
          type: string
          description: New  card number- The new generated card number
          format: uppercase
        effectiveDate:
          type: string
          description: Effective Date-Date that the fraud card transfer is effective
          format: date
        transferFromAccount:
          type: string
          description: Transfer From Account- The account asscoicated to the old card
          format: uppercase
    CardsSecureCodeResp:
      required:
        - cardNumber
      type: object
      properties:
        cardNumber:
          type: string
          description: >-
            Card Number -Number that is embossed on the plastic card. Enter a
            value inthis field only if the card number is different from the
            post-toaccount number
          format: uppercase
    UpdateCardProfileReq:
      required:
        - businessUnit
        - cardNumber
        - cardSequence
        - postToAccountNumber
      type: object
      properties:
        businessUnit:
          type: number
          description: >-
            Business Unit -Identification number of the organization associated
            with thisAccount Base Segment record. The values are 001–998.
        cardSequence:
          type: number
          description: Card sequence- This a static value value 0001 should be passed
        postToAccountNumber:
          maxLength: 19
          type: string
          description: >-
            Post to account number-Identification number of the Account Base
            Segment record towhich CMS posts transactions received for this
            Embosser record
          format: uppercase
        cardNumber:
          maxLength: 19
          type: string
          description: >-
            CARD NUMBER-Number that is embossed on the plastic card. Enter a
            value inthis field only if the card number is different from the
            post-toaccount number
          format: uppercase
    UpdateCardsProfileResp:
      required:
        - businessUnit
        - cardNumber
        - cardSequence
        - postToAccountNumber
      type: object
      properties:
        cardholderType:
          type: string
          description: >-
            Cardholder Type-Code that indicates whether the cardholder is the
            primarycardholder or an additional cardholder associated with
            theaccount. The value for this field is set in the card-adding
            processwith the first cardholder designated as the primary
            cardholderand the other cardholders as additional cardholders. The
            values are 0 =Additional cardholder 1=Primary cardholder
          enum:
            - 0 - Additional
            - 1 - Primary
        businessUnit:
          type: number
          description: >-
            Business Unit -Identification number of the organization associated
            with thisAccount Base Segment record. The values are 001–998.
        cardSequence:
          type: number
          description: Card sequence- This a static value value 0001 should be passed
        postToAccountNumber:
          maxLength: 19
          type: string
          description: >-
            Post to account number-Identification number of the Account Base
            Segment record towhich CMS posts transactions received for this
            Embosser record
          format: uppercase
        cardNumber:
          maxLength: 19
          type: string
          description: >-
            CARD NUMBER-Number that is embossed on the plastic card. Enter a
            value inthis field only if the card number is different from the
            post-toaccount number
          format: uppercase
    UpdateCardPinReq:
      required:
        - businessUnit
        - requestedPinBlock
        - cardNumber
      type: object
      properties:
        cardNumber:
          type: string
          description: >-
            Card Number-if the service is sucessiful, the response the updated
            card number will be send this will
          format: uppercase
        businessUnit:
          type: number
          description: >-
            Business Unit -Identification number of the organization associated
            with thisAccount Base Segment record. The values are 001–998.
        requestedPinBlock:
          type: string
          description: >-
            Requested pin block(New pin block)-The new pin block should be
            provided, This will be new pin Enter by customer
    UpdateCardPinResponse:
      type: object
      properties:
        userFiller:
          type: string
          description: User filler-This is filler used for future purpose
        filler:
          type: string
          description: Vgs filler- This is filler used for future purpose
        cardNumber:
          type: string
          description: >-
            Card Number-if the service is sucessiful, the response the updated
            card number will be send this will
          format: uppercase
    UpdateCardTransferReq:
      required:
        - accountNumber
        - action
        - blockCode
        - cardNumber
        - cardReplacementIndicator
        - cardSequenceNumber
        - effectiveDate
        - operatorId
        - product
        - startDate
        - terminalId
        - transferToAccount
        - transferToCustomer
      type: object
      properties:
        blockCode:
          maxLength: 1
          type: string
          description: >-
            Block code-Block code to apply to the transfer cardThe values are
            blank(or space) and A to Z
          format: uppercase
        product:
          maximum: 999
          minimum: 0
          type: number
          description: >-
            Product - Product associated with this Account. The values are
            001–998
        businessUnit:
          maximum: 999
          minimum: 0
          type: number
          description: >-
            Business Unit -Identification number of the organization associated
            with thisAccount Base Segment record. The values are 001–998.
        cardReplacementIndicator:
          type: string
          description: >-
            Card replacement indicator-Code that indicates whether CMS replaces
            the transfer card bygenerating a new Embosser record on the original
            account. The values are 0=Replace lost/stolen/fraud card (Default),
            1=Do not replace lost/stolen/fraud card
          enum:
            - 0 - Replace
            - 1 - Do Not Replace
        terminalId:
          maxLength: 4
          type: string
          description: Terminal id- The terminal from where the service was called
          format: uppercase
        accountNumber:
          maxLength: 19
          type: string
          description: Account number-Account currently associated with the card
          format: uppercase
        customerBusinessUnit:
          maximum: 999
          minimum: 0
          type: number
          description: >-
            Card transfer org-Identification number of the organization
            associated with thisAccount Base Segment record. The values are
            001–9
        transferToAccount:
          maxLength: 19
          type: string
          description: >-
            Transfer to account-Number of the account to which you want to
            transfer the cardYou can enter a specific account number or enter a
            slash (/) ifthe auto-generation functionality is active for account
            numbers.
          format: uppercase
        transferToCustomer:
          maxLength: 19
          type: string
          description: >-
            Transfer to customer-Number that identifies the Customer
            Name/Address recordassociated with the transfer-to accountIf you are
            transferring the card to an existing accountdo notmake an entry in
            the CUSTOMER fieldCMS uses the customernumber associated with the
            existing account
          format: uppercase
        signonName:
          type: string
          description: signon name
        action:
          type: string
          description: >-
            Action-This field issystem-generated; you cannot modify it. The
            values are R=Reverse a card transfer, T=Transfer the card (lost,
            stolen, or fraud).
          enum:
            - T - Transfer
            - R - Reversal
        securitySignon:
          type: string
          description: security signon
        operatorId:
          maxLength: 3
          type: string
          description: Operator id-user signon operator id
          format: uppercase
        cardNumber:
          maxLength: 19
          type: string
          description: >-
            CARD NUMBER-Number that is embossed on the plastic card. Enter a
            value inthis field only if the card number is different from the
            post-toaccount number
          format: uppercase
        effectiveDate:
          type: string
          description: >-
            Effective date-Date that the fraud card transfer is effective The
            value must be a date less than or equal to today’sdateThe default
            value is today’s date. If you enter a future date The system will
            abend
          format: date
        cardSequenceNumber:
          maximum: 9999
          minimum: 1
          type: number
          description: Card sequence- This a static value value 0001 should be passed
        startDate:
          type: string
          description: Start date- the date when the serivce was called
          format: date
    CardsBlockUnblockReq:
      required:
        - businessUnit
        - cardNumber
        - cardSequence
        - postToAccountNumber
      type: object
      properties:
        businessUnit:
          type: number
          description: >-
            Business Unit -Identification number of the organization associated
            with thisAccount Base Segment record. The values are 001–998.
        cardSequence:
          type: number
          description: Card sequence- This a static value value 0001 shouldbe passed
        postToAccountNumber:
          maxLength: 19
          type: string
          description: >-
            Post to account number-Identification number of the Account Base
            Segment record towhich CMS posts transactions received for this
            Embosser record
          format: uppercase
        cardNumber:
          maxLength: 19
          type: string
          description: >-
            CARD NUMBER-Number that is embossed on the plastic card. Enter a
            value inthis field only if the card number is different from the
            post-toaccount number
          format: uppercase
    CardsBlockUnblockResp:
      required:
        - businessUnit
        - cardNumber
        - cardSequence
        - postToAccountNumber
      type: object
      properties:
        cardholderType:
          type: string
          description: >-
            Card holder type-'Code that indicates whether the cardholder is the
            primarycardholder or an additional cardholder associated with
            theaccount. The value for this field is set in the card-adding
            processwith the first cardholder designated as the primary
            cardholderand the other cardholders as additional cardholders,
            values are 0=Additional cardholder, 1=Primary cardholder
          enum:
            - 1 - Primary
            - 0 - Additional
        blockCode:
          type: string
          description: >-
            Block code-The block code assigned to the Embosser record, Blcok
            code values can be be A- Z or SPACES
          enum:
            - X
            - E
            - F
            - G
            - ' '
        blockDate:
          type: string
          description: Card block date-The date on which card is blocked
          format: uppercase
        businessUnit:
          type: number
          description: >-
            Business Unit -Identification number of the organization associated
            with thisAccount Base Segment record. The values are 001–998.
        cardSequence:
          type: number
          description: Card sequence- This a static value value 0001 should be passed
        postToAccountNumber:
          maxLength: 19
          type: string
          description: >-
            Post to account number-Identification number of the Account Base
            Segment record towhich CMS posts transactions received for this
            Embosser record
          format: uppercase
        cardNumber:
          maxLength: 19
          type: string
          description: >-
            CARD NUMBER-Number that is embossed on the plastic card. Enter a
            value inthis field only if the card number is different from the
            post-toaccount number
          format: uppercase
        warningCode1:
          type: string
          description: >-
            Warning Code1 -This field determine whether to authorize or decline
            authorizations for this Embosser record (card), These are display
            fieldscannot change the values The values are 0 =Normal
            authorizations (Default), 1=Decline, 2=Decline and pick up,3=Decline
            and pick up for fraud or lost/stolencard,4=Decline with
            referral,5=Approve after verifying cardholder ID,6=Decline for
            suspected fraud,8=Decline with a user exit,9=VIP account; always
            approve
          enum:
            - 0 - No Action
            - ' '
            - 1 - Decline Auth
            - 2 - Decline Pickup
            - 3 - Decline Fraud
            - 4 - Decline Refer
            - 6 - Decline Susp Fraud
            - 8 - Decline User Exit
            - 9 - Approve Tip
    UpdateCardLimitReq:
      required:
        - businessUnit
        - cardNumber
        - cardSequence
        - postToAccountNumber
      type: object
      properties:
        businessUnit:
          type: number
          description: >-
            Business Unit -Identification number of the organization associated
            with thisAccount Base Segment record. The values are 001–998.
        cardSequence:
          type: number
          description: Card sequence- This a static value value 0001 should be passed
        postToAccountNumber:
          maxLength: 19
          type: string
          description: >-
            Post to account number-Identification number of the Account Base
            Segment record towhich CMS posts transactions received for this
            Embosser record
          format: uppercase
        cardNumber:
          maxLength: 19
          type: string
          description: >-
            CARD NUMBER-Number that is embossed on the plastic card. Enter a
            value inthis field only if the card number is different from the
            post-toaccount number
          format: uppercase
    UpdateCardLimitResp:
      required:
        - businessUnit
        - cardNumber
        - cardSequence
        - postToAccountNumber
      type: object
      properties:
        businessUnit:
          type: number
          description: >-
            Business Unit -Identification number of the organization associated
            with thisAccount Base Segment record. The values are 001–998.
        cardSequence:
          type: number
          description: Card sequence- This a static value value 0001 should be passed
        maximumNumberRetailAuthorizationsAllowed:
          type: number
          description: >-
            Maximum number retail authorization-Maximum number of retail
            authorizations allowed for thisEmbosser record for the frequency
            defined in the FREQ field
        maximumAmountSingleATMTransactionAllowed:
          type: string
          description: >-
            Maximum amount SINGLE ATM Transaction-Maximum authorization amount
            in monetary units and subunitsof a single ATM transaction allowed
            for this Embosser recordfor the frequency defined in the FREQ field
          default: 0
        singleOTCCashAuthorizationAllowed:
          type: string
          description: >-
            Maximum Amount Single OTC cash authorization allowed-Maximum amount
            in monetary units and subunits of OTCauthorizations allowed for this
            Embosser record for thefrequency defined in the FREQ field
          default: 0
        postToAccountNumber:
          maxLength: 19
          type: string
          description: >-
            Post to account number-Identification number of the Account Base
            Segment record towhich CMS posts transactions received for this
            Embosser record
          format: uppercase
        maximumAmountATMCashAuthorizationsAllowed:
          type: string
          description: >-
            Maximum amount ATM cash authorization-Maximum amount in monetary
            units and subunits of ATM cashauthorizations allowed for this
            Embosser record for thefrequency defined in the FREQ field
          default: 0
        maximumNumberOTCAuthorizationsAllowed:
          type: number
          description: >-
            Maximum number OTC  authorization-Maximum number of OTC
            authorizations allowed for thisEmbosser record for the frequency
            defined in the FREQ field
        maximumNumberATMCashAuthorizationsAllowed:
          type: number
          description: >-
            Maximum number ATM cash authorization-Maximum number of ATM cash
            authorizations allowed for thisEmbosser record for the frequency
            defined in the FREQ field
        singleRetailAuthorizationAllowed:
          type: string
          description: >-
            Maximum Amount Single retail authorization allowed- Maximum amount
            in monetary units and subunits of OTCauthorizations allowed for this
            Embosser record for thefrequency defined in the FREQ field.
          default: 0
        maximumAmountRetailAuthorizationsAllowed:
          type: string
          description: >-
            Maximum amount retail authorization-Maximum amount in monetary units
            and subunits of retailauthorizations allowed for this Embosser
            record for thefrequency defined in the FREQ field
          default: 0
        maximumAuthorizationsFrequnecy:
          type: string
          description: >-
            Maximum authorization frequency-Code that indicates the frequency
            for the maximumauthorization parameters The values are 0=Not
            used,1=Daily,2=Cycle-to-date,3=Year-to-date
          enum:
            - 0 - Frequency Not Used
            - 1 - Daily Frequency
            - 2 - Cycle To Date Frequency
            - 3 - Year To Date Frequency
        maximumAmountOTCCashAuthorizationsAllowed:
          type: string
          description: >-
            Maximum amount OTC cash authorization-Maximum amount in monetary
            units and subunits of OTC cashauthorizations allowed for this
            Embosser record for thefrequency defined in the FREQ field
        cardNumber:
          maxLength: 19
          type: string
          format: uppercase
          description: >-
            CARD NUMBER-Number that is embossed on the plastic card. Enter a
            value inthis field only if the card number is different from the
            post-toaccount number
    AccountsBlockUnblockReq:
      required:
        - product
        - billingAcctInd
        - businessUnit
        - accountNumber
      type: object
      properties:
        businessUnit:
          type: number
          default: 0
          example: 100
          description: >-
            Business Unit -Identification number of the organization associated
            with thisAccount Base Segment record. The values are 001–998
        accountNumber:
          type: string
          maxLength: 19
          format: uppercase
          example: 100001NNNNN0481
          description: >-
            Account- Customer account number. Must be numeric and greater than
            zero. Max length = 19. Should be a valid Account number.
        product:
          type: number
          example: 1
          description: Product associated with this Account. The values are 001–998
        billingAcctInd:
          type: number
          example: 0
          description: >-
            ACCOUNT TYPE-Code that indicates whether the account being added is
            atransaction (cardholder), billing, control, or diversion account
        blockCode1:
          type: string
          example: X
          description: >-
            Block code 1-Field that identifies the block codes assigned to this
            account. Block codes control specific processing options at
            theaccount level. Valid block codes are the letters A to Z and
            spaces
        blockCode2:
          type: string
          example: ' '
          description: >-
            Block code 2-Field that identifies the block codes assigned to this
            account. Block codes control specific processing options at
            theaccount level. Valid block codes are the letters A to Z and
            spaces
    AccountsBlockUnblockResp:
      required:
        - accountNumber
        - billingAcctInd
        - businessUnit
        - product
      type: object
      properties:
        product:
          type: number
          example: 1
          description: Product associated with this Account. The values are 001–998
        businessUnit:
          type: number
          example: 100
          description: >-
            Business Unit -Identification number of the organization associated
            with thisAccount Base Segment record. The values are 001–998 
        accountNumber:
          maxLength: 19
          type: string
          example: 0001000010000510481
          description: >-
            Account- Customer account number. Must be numeric and greater than
            zero. Max length = 19. Should be a valid Account number.
          format: uppercase
        billingAcctInd:
          type: number
          example: 0
          description: >-
            ACCOUNT TYPE-Code that indicates whether the account being added is
            atransaction (cardholder), billing, control, or diversion account
        blockCode1:
          type: string
          example: X
          description: >-
            Block code 1-Field that identifies the block codes assigned to this
            account. Block codes control specific processing options at
            theaccount level. Valid block codes are the letters A to Z and
            spaces
        blockCode2:
          type: string
          example: ' '
          description: >-
            Block code 2-Field that identifies the block codes assigned to this
            account. Block codes control specific processing options at
            theaccount level. Valid block codes are the letters A to Z and
            spaces
        blockCodeDate1:
          type: string
          format: uppercase
          example: 01/10/2021
          description: >-
            BLOCK DATE 1-Date on which block code 1 was entered. The value in
            this fieldis system-generated; you cannot change it
        blockCodeDate2:
          type: string
          format: uppercase
          example: 00/00/0000
          description: >-
            BLOCK DATE 2-Date on which block code 1 was entered. The value in
            this fieldis system-generated; you cannot change it
    ErrorList1:
      type: array
      items:
        type: object
        properties:
          errorCode:
            type: string
            example: XXXXXXXX
            description: Error code associated with the response
          errorMessage:
            type: string
            example: Some message from the service
            description: Error message associated with the response
  examples:
    BlockAccount:
      value:
        businessUnit: '100'
        accountNumber: 100001NNNXX0481
        product: '001'
        billingAcctInd: '0'
        blockCode1: X
        blockCode2: ' '
    400-Errors:
      value:
        erorrCode: XXXXXXXX
        errorMessage: Some message from the service
    401-Errors:
      value:
        erorrCode: XXXXXXXX
        errorMessage: Some message from the service
    404-Errors:
      value:
        erorrCode: XXXXXXXX
        errorMessage: Some message from the service
    500-Errors:
      value:
        erorrCode: XXXXXXXX
        errorMessage: Some message from the service
    503-Errors:
      value:
        erorrCode: XXXXXXXX
        errorMessage: Some message from the service
    504-Errors:
      value:
        erorrCode: XXXXXXXX
        errorMessage: Some message from the service